parameters:
#    studio_home.example.class: Studio\HomeBundle\Example

services:
#    studio_home.example:
#        class: %studio_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
